//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irbis.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int NomenclatureID { get; set; }
        public int Quantity { get; set; }
        public decimal SalePrice { get; set; }
        public int CustomerID { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Nomenclatures Nomenclatures { get; set; }
    }
}
